### ISSUE TITLE
[Fix] MemoryAddEditView 로직 오류 수정

### ISSUE THREAD

**Issue by yurim830** [TEAM-OMG-iOS/TravelTale#73]
### 1. MemoryAddEditView에 처음 진입 시 confirmButton이 활성화되어있는 오류 해결
<img width="200" alt="image" src="https://github.com/TEAM-OMG-iOS/TravelTale/assets/157277372/37c4229b-b211-470b-8982-6c9c72175626">

### 2. areaLabel 바인딩 수정
여행 생성 상황에서 area를 선택하지 않으면 travel.area = "미정"으로 저장되므로,
내 쪽에서는 판단 로직 없이 areaLabel에 바로 travel.area 대입하기
`areaLabel.text = travel.area ?? "미정"`  -> `areaLabel.text = travel.area`

### TODO(1)
- [x] checkTextViewContent 함수 수정
  - [x] 함수명 직관적으로 변경 -> configureConfirmButton
  - [x] textView textColor 수정하는 코드 삭제 (불필요함)
- [x] 뷰 그리는 단계에서 configureConfirmButton 함수 호출

### TODO(2)
- [x] 완료
